export const ActionTypes = {
  SET_DISPLAYED_PRODUCTS_BY_BRAND: "SET_DISPLAYED_PRODUCTS_BY_BRAND",
  SET_DISPLAYED_PRODUCTS_BY_PRICE: "SET_DISPLAYED_PRODUCTS_BY_PRICE",
  SET_CART_PRODUCTS: "SET_CART_PRODUCTS",
  DELETE_CART_ITEM: "DELETE_CART_ITEM",
  CHANGE_TOTAL_COST: "CHANGE_TOTAL_COST",
  REMOVE_PRICE_FILTER: "REMOVE_PRICE_FILTER",
};
